name: CodeAlpha CI/CD Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Source Code
      uses: actions/checkout@v3

    - name: Log in to Azure Container Registry (ACR)
      uses: azure/docker-login@v1
      with:
        login-server: codealpharegistry99.azurecr.io
        username: codealpharegistry99
        password: ${{ secrets.ACR_PASSWORD }}

    - name: Build and Push Docker Image
      run: |
        docker build . -t codealpharegistry99.azurecr.io/codealpha-app:latest
        docker push codealpharegistry99.azurecr.io/codealpha-app:latest

    - name: Trigger Azure Container Deployment Webhook
      run: |
        curl -X POST "${{ secrets.AZURE_WEBAPP_WEBHOOK }}"
